version: '3.8'

services:
  # --- VERİTABANLARI VE MESAJLAŞMA ---
  db-users:
    image: mongo:latest
    container_name: db-users
    networks:
      - micro-network
    ports:
      - "27017:27017"

  db-products:
    image: postgres:latest
    container_name: db-products
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    networks:
      - micro-network
    ports:
      - "5432:5432"

  db-orders:
    image: mysql:latest
    container_name: db-orders
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orders_db
    networks:
      - micro-network
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - micro-network
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - micro-network
    ports:
      - "9200:9200"

  # --- MİKROSERVİSLER ---
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq
      - db-users
    networks:
      - micro-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-orders:3306/orders_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - db-orders
      - rabbitmq
    networks:
      - micro-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5000:5000"
    command: python app.py
    environment:
      - DATABASE_URL=postgresql://user:password@db-products:5432/products_db
      - RABBITMQ_HOST=rabbitmq
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db-products
      - rabbitmq
      - elasticsearch
    networks:
      - micro-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db-users:27017/users_db
      - JWT_SECRET=fisek_gibi_proje_2026
    depends_on:
      - db-users
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge
