version: '3.8'

services:
  # --- VERİTABANLARI ---
  db-users:
    image: mongo:latest
    ports:
      - "27017:27017"

  db-products:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"

  db-orders:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orders_db
    ports:
      - "3306:3306"

  # --- MESAJLAŞMA (RabbitMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Mesaj iletim portu
      - "15672:15672" # Panel portu (Kullanıcı: guest, Şifre: guest)

  # --- SERVİS KEŞFİ (Consul) ---
  #consul:
  #  image: consul:latest
  #  ports:
  #    - "8500:8500"

  # --- API GATEWAY (Node.js) ---
  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - rabbitmq
    networks:
      - micro-network

  # --- ORDER SERVICE (Java) ---
  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-orders:3306/orders_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - db-orders
      - rabbitmq
    networks:
      - micro-network

  # --- PRODUCT SERVICE (Python) ---
  product-service:
    build: ./product-service
    environment:
      - DB_HOST=db-products
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - db-products
      - rabbitmq
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge