server:
  port: 8080

spring:
  datasource:
    # Veritabanı yoksa otomatik oluşturur
    url: jdbc:mysql://localhost:3306/orders_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: password # BURAYA KENDİ MYSQL ŞİFRENİ YAZ KUZEN
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # Tabloları otomatik oluşturur
    show-sql: true # Konsolda SQL sorgularını görmeni sağlar
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # RabbitMQ Ayarları
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Hata ayıklama logları
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG